# Generated by Django 6.0.5 on 2026-05-11 20:30

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del área común')),
                ('capacidad_maxima', models.PositiveIntegerField(verbose_name='Aforo máximo permitido')),
                ('aforo_actual', models.PositiveIntegerField(default=0, verbose_name='Aforo actual')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('MANTENIMIENTO', 'En Mantenimiento'), ('RESTRINGIDO', 'Restringido')], default='DISPONIBLE', max_length=20, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Área Común',
                'verbose_name_plural': 'Áreas Comunes',
            },
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, verbose_name='Número de habitación')),
                ('tipo', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('DOBLE', 'Doble'), ('SUITE', 'Suite'), ('FAMILIAR', 'Familiar')], default='INDIVIDUAL', max_length=20, verbose_name='Tipo de habitación')),
                ('capacidad', models.PositiveIntegerField(verbose_name='Capacidad de huéspedes')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio base por noche')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'En Mantenimiento'), ('SUCIA', 'Sucia / Limpieza requerida')], default='DISPONIBLE', max_length=20, verbose_name='Estado de la habitación')),
            ],
            options={
                'verbose_name': 'Habitación',
                'verbose_name_plural': 'Habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre(s)')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido(s)')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI (Documento Nacional de Identidad)'), ('PASAPORTE', 'Pasaporte'), ('CE', 'Carné de Extranjería')], default='DNI', max_length=20, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=20, unique=True, verbose_name='Número de Documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('preferencias_notas', models.TextField(blank=True, null=True, verbose_name='Preferencias / Notas Especiales')),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del suministro / artículo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('stock_actual', models.PositiveIntegerField(default=0, verbose_name='Stock actual')),
                ('stock_minimo', models.PositiveIntegerField(default=5, verbose_name='Stock mínimo (alerta de reabastecimiento)')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Precio de venta unitario (para cargos extra)')),
            ],
            options={
                'verbose_name': 'Inventario / Suministro',
                'verbose_name_plural': 'Inventarios / Suministros',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la sede')),
                ('direccion', models.CharField(max_length=255, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': 'Sedes',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('RECEPCIONISTA', 'Recepcionista'), ('MANTENIMIENTO', 'Personal de Mantenimiento'), ('LIMPIEZA', 'Personal de Limpieza')], default='RECEPCIONISTA', max_length=20, verbose_name='Rol del usuario')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('sede_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='hotel.sede', verbose_name='Sede asignada')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_checkin', models.DateTimeField(verbose_name='Fecha y hora de Check-in real')),
                ('fecha_checkout', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de Check-out real')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones / Estado del cliente')),
                ('checkout_registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Check-out registrado por')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkins_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por (Recepción)')),
            ],
            options={
                'verbose_name': 'Estadía',
                'verbose_name_plural': 'Estadías',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título / Resumen de la incidencia')),
                ('descripcion', models.TextField(verbose_name='Descripción detallada')),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de reporte')),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de resolución')),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('RESUELTO', 'Resuelto'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20, verbose_name='Estado de la incidencia')),
                ('area_comun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='hotel.areacomun', verbose_name='Área común afectada')),
                ('asignado_a', models.ForeignKey(blank=True, limit_choices_to={'role': 'MANTENIMIENTO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a (Personal de Mantenimiento)')),
                ('habitacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='hotel.habitacion', verbose_name='Habitación afectada')),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_reportadas', to=settings.AUTH_USER_MODEL, verbose_name='Reportado por')),
            ],
            options={
                'verbose_name': 'Incidencia de Mantenimiento',
                'verbose_name_plural': 'Incidencias de Mantenimiento',
                'ordering': ['-prioridad', 'fecha_reporte'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción del cargo o servicio')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('fecha_consumo', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de consumo')),
                ('pagado', models.BooleanField(default=False, verbose_name='¿Pagado de inmediato?')),
                ('estadia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_extra', to='hotel.estadia', verbose_name='Estadía')),
                ('inventario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos_asociados', to='hotel.inventario', verbose_name='Artículo de Inventario (Suministro consumido)')),
            ],
            options={
                'verbose_name': 'Consumo Extra',
                'verbose_name_plural': 'Consumos Extra',
            },
        ),
        migrations.CreateModel(
            name='RegistroAforoAreaComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de ingreso')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de salida')),
                ('area_comun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_aforo', to='hotel.areacomun', verbose_name='Área Común')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_aforo', to='hotel.huesped', verbose_name='Huésped')),
            ],
            options={
                'verbose_name': 'Registro de Aforo',
                'verbose_name_plural': 'Registros de Aforo',
                'ordering': ['-fecha_ingreso'],
            },
        ),
        migrations.CreateModel(
            name='RegistroLimpieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de finalización')),
                ('estado', models.CharField(choices=[('EN_PROGRESO', 'En Progreso'), ('COMPLETADO', 'Completado'), ('INSPECCIONADO', 'Inspeccionado y Aprobado')], default='EN_PROGRESO', max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_limpieza', to='hotel.habitacion', verbose_name='Habitación')),
                ('personal_limpieza', models.ForeignKey(blank=True, limit_choices_to={'role': 'LIMPIEZA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpiezas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Personal de limpieza')),
            ],
            options={
                'verbose_name': 'Registro de Limpieza',
                'verbose_name_plural': 'Registros de Limpieza',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_reserva', models.CharField(max_length=20, unique=True, verbose_name='Código de Reserva')),
                ('fecha_entrada', models.DateField(verbose_name='Fecha de Entrada (Check-in)')),
                ('fecha_salida', models.DateField(verbose_name='Fecha de Salida (Check-out)')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Reserva')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente / Pago Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso (Hospedado)'), ('COMPLETADA', 'Completada / Check-out'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado de la reserva')),
                ('tarifa_aplicada', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa total aplicada (Precio pactado)')),
                ('origen', models.CharField(choices=[('DIRECTO', 'Reserva Directa'), ('BOOKING', 'Booking.com'), ('EXPEDIA', 'Expedia'), ('AIRBNB', 'Airbnb')], default='DIRECTO', max_length=20, verbose_name='Origen de la reserva (OTA)')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.habitacion', verbose_name='Habitación')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='hotel.huesped', verbose_name='Huésped')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.AddField(
            model_name='estadia',
            name='reserva',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='estadia', to='hotel.reserva', verbose_name='Reserva Asociada'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventarios', to='hotel.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hotel.sede', verbose_name='Sede'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_comunes', to='hotel.sede', verbose_name='Sede'),
        ),
        migrations.AlterUniqueTogether(
            name='inventario',
            unique_together={('sede', 'nombre')},
        ),
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together={('sede', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='areacomun',
            unique_together={('sede', 'nombre')},
        ),
    ]
