# Generated by Django 6.0.5 on 2026-05-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('INVENTORY', 'Encargado de Inventario'), ('USER', 'Usuario / Cliente'), ('RECEPCIONISTA', 'Recepcionista'), ('MANTENIMIENTO', 'Personal de Mantenimiento'), ('LIMPIEZA', 'Personal de Limpieza')], default='USER', max_length=20, verbose_name='Rol del usuario'),
        ),
    ]
