# Generated by Django 6.0.5 on 2026-05-14 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hotel', '0002_alter_usuario_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_clean_rooms', 'Can clean rooms'), ('can_do_maintenance', 'Can do maintenance'), ('can_manage_users', 'Can manage users'), ('can_manage_roles', 'Can manage roles'), ('can_manage_inventory', 'Can manage inventory'), ('can_manage_reservations', 'Can manage reservations'), ('can_view_reports', 'Can view reports')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='asignado_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__permissions__codename': 'can_do_maintenance'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a (Personal de Mantenimiento)'),
        ),
        migrations.AlterField(
            model_name='registrolimpieza',
            name='personal_limpieza',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__permissions__codename': 'can_clean_rooms'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='limpiezas_asignadas', to=settings.AUTH_USER_MODEL, verbose_name='Personal de limpieza'),
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='role',
        ),
        migrations.AddField(
            model_name='usuario',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='auth.group', verbose_name='Rol del usuario'),
        ),
    ]
