# Generated by Django 6.0.5 on 2026-05-14 17:40

from django.db import migrations


def create_admin_role(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Administrador')

def remove_admin_role(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='Administrador').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_alter_usuario_options_alter_incidencia_asignado_a_and_more'),
    ]

    operations = [
        migrations.RunPython(create_admin_role, remove_admin_role),
    ]
