# Generated by Django 6.0.5 on 2026-05-15 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_auto_20260514_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='sede',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hotel.sede', verbose_name='Sede'),
        ),
    ]
