# Generated by Django 6.0.5 on 2026-05-15 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_alter_habitacion_sede'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together=set(),
        ),
    ]
