# Generated by Django 6.0.5 on 2026-05-15 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_alter_habitacion_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la planta')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número de planta')),
            ],
            options={
                'verbose_name': 'Planta',
                'verbose_name_plural': 'Plantas',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='habitacion',
            name='planta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='habitaciones', to='hotel.planta', verbose_name='Planta/Piso'),
        ),
    ]
