# Generated by Django 6.0.5 on 2026-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_planta_habitacion_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='categoria',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='areas/', verbose_name='Imagen del área'),
        ),
    ]
