# Generated by Django 6.0.5 on 2026-06-17 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_areacomun_categoria_areacomun_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('metodo', models.CharField(choices=[('TARJETA', 'Tarjeta de Crédito/Débito (Pasarela)'), ('YAPE', 'Yape'), ('PLIN', 'Plin'), ('EFECTIVO', 'Efectivo en Recepción')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente (Por Verificar)'), ('COMPLETADO', 'Completado (Confirmado)'), ('FALLIDO', 'Fallido / Rechazado')], default='PENDIENTE', max_length=20, verbose_name='Estado del Pago')),
                ('comprobante_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Transacción / Código Operación')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación Manual')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='hotel.reserva', verbose_name='Reserva Asociada')),
            ],
            options={
                'verbose_name': 'Registro de Pago',
                'verbose_name_plural': 'Registros de Pagos',
                'ordering': ['-fecha_pago'],
            },
        ),
    ]
