# Generated by Django 6.0.5 on 2026-05-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_areacomun_categoria_areacomun_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='tipo',
            field=models.CharField(choices=[('SUMINISTRO', 'Suministro'), ('INVENTARIO', 'Inventario')], default='SUMINISTRO', max_length=20, verbose_name='Tipo de artículo'),
        ),
    ]
