# Generated by Django 6.0.5 on 2026-05-20 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_areacomun_categoria_areacomun_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('can_clean_rooms', 'Can clean rooms'), ('can_do_maintenance', 'Can do maintenance'), ('can_manage_users', 'Can manage users'), ('can_manage_roles', 'Can manage roles'), ('can_manage_inventory', 'Can manage inventory'), ('can_manage_reservations', 'Can manage reservations'), ('can_view_reports', 'Can view reports'), ('can_manage_rooms', 'Can manage rooms')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
