# Generated by Django 6.0.5 on 2026-05-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0008_areacomun_categoria_areacomun_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Habitación activa?'),
        ),
    ]
