# Generated by Django 6.0.5 on 2026-05-20 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_usuario_options'),
        ('hotel', '0009_inventario_tipo'),
    ]

    operations = [
    ]
