# Generated by Django 6.0.5 on 2026-05-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_habitacion_is_active'),
        ('hotel', '0010_merge_0009_alter_usuario_options_0009_inventario_tipo'),
    ]

    operations = [
    ]
