# Generated by Django 6.0.5 on 2026-05-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_merge_20260520_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='¿Área activa?'),
        ),
    ]
