# Generated by Django 6.0.5 on 2026-05-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_areacomun_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'En Mantenimiento'), ('SUCIA', 'Sucia / Limpieza requerida'), ('RESTRINGIDO', 'Restringido')], default='DISPONIBLE', max_length=20, verbose_name='Estado'),
        ),
    ]
