# Generated by Django 6.0.5 on 2026-05-21 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_alter_areacomun_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Activo'), ('INACTIVE', 'Inactivo')], default='ACTIVE', max_length=20, verbose_name='Estado'),
        ),
    ]
