# Generated by Django 6.0.5 on 2026-06-17 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0015_usuario_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_comprobante', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], max_length=10, verbose_name='Tipo de Comprobante')),
                ('serie', models.CharField(max_length=4, verbose_name='Serie')),
                ('numero', models.PositiveIntegerField(verbose_name='Número Correlativo')),
                ('documento_cliente', models.CharField(max_length=20, verbose_name='Documento del Cliente')),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia')], max_length=20, verbose_name='Método de Pago')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Total')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Emisión')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes', to='hotel.reserva', verbose_name='Reserva Asociada')),
            ],
            options={
                'verbose_name': 'Comprobante de Pago',
                'verbose_name_plural': 'Comprobantes de Pago',
                'unique_together': {('tipo_comprobante', 'serie', 'numero')},
            },
        ),
    ]
