# Generated by Django 6.0.5 on 2026-06-17 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0016_comprobante'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registroaforoareacomun',
            options={'ordering': ['-fecha_ingreso_programada'], 'verbose_name': 'Registro de Aforo', 'verbose_name_plural': 'Registros de Aforo'},
        ),
        migrations.RemoveField(
            model_name='registroaforoareacomun',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='registroaforoareacomun',
            name='fecha_salida',
        ),
        migrations.AddField(
            model_name='registroaforoareacomun',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADA', 'Confirmada'), ('EN_CURSO', 'En Curso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='registroaforoareacomun',
            name='fecha_ingreso_programada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de ingreso programada'),
        ),
        migrations.AddField(
            model_name='registroaforoareacomun',
            name='fecha_ingreso_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de ingreso real'),
        ),
        migrations.AddField(
            model_name='registroaforoareacomun',
            name='fecha_salida_programada',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de salida programada'),
        ),
        migrations.AddField(
            model_name='registroaforoareacomun',
            name='fecha_salida_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de salida real'),
        ),
        migrations.AddField(
            model_name='registroaforoareacomun',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='registroaforoareacomun',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aforos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
    ]
