# Generated by Django 6.0.5 on 2026-06-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_pago'),
        ('hotel', '0016_comprobante'),
    ]

    operations = [
    ]
