# Generated by Django 6.0.5 on 2026-06-17 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_merge_0009_pago_0016_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la temporada / evento')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Finalización')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Temporada activa?')),
            ],
            options={
                'verbose_name': 'Temporada Dinámica',
                'verbose_name_plural': 'Temporadas Dinámicas',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
