# Generated by Django 6.0.5 on 2026-06-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_temporada_delete_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporada',
            name='porcentaje',
            field=models.IntegerField(default=0, help_text='Porcentaje de variación tarifaria'),
        ),
    ]
