# Generated by Django 6.0.5 on 2026-06-18 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_temporada_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='porcentaje',
            field=models.IntegerField(default=0, help_text='Porcentaje de variación'),
        ),
    ]
