# Generated by Django 6.0.5 on 2026-06-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_alter_registroaforoareacomun_options_and_more'),
        ('hotel', '0020_alter_temporada_porcentaje'),
    ]

    operations = [
    ]
