# Generated by Django 6.0.5 on 2026-06-19 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_merge_20260618_0851'),
        ('hotel', '0021_merge_20260618_0917'),
    ]

    operations = [
    ]
