# Generated by Django 6.0.5 on 2026-06-19 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_merge_20260619_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveSmallIntegerField(verbose_name='Calificación (1-5)')),
                ('comentario', models.TextField(verbose_name='Comentario')),
                ('respuesta_administrador', models.TextField(blank=True, null=True, verbose_name='Respuesta del administrador')),
                ('es_inapropiada', models.BooleanField(default=False, verbose_name='Marcada como inapropiada')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('estadia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resena', to='hotel.estadia', verbose_name='Estadía')),
            ],
            options={
                'verbose_name': 'Reseña',
                'verbose_name_plural': 'Reseñas',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['es_inapropiada'], name='hotel_resen_es_inap_168350_idx'), models.Index(fields=['fecha_creacion'], name='hotel_resen_fecha_c_ac3e32_idx')],
            },
        ),
    ]
